
python3 render_electric_clean.py electric_states/lespaul_clean_both_nonoise_stereo
python3 render_electric_clean.py electric_states/lespaul_clean_bridge_nonoise_stereo
python3 render_electric_clean.py electric_states/lespaul_clean_neck_nonoise_stereo
python3 render_electric_clean.py electric_states/peregrine_clean_both_nonoise_stereo
python3 render_electric_clean.py electric_states/peregrine_clean_bridge_nonoise_stereo
python3 render_electric_clean.py electric_states/peregrine_clean_neck_nonoise_stereo
